language: bash
sudo: false
env:
- DISTRO=ubuntu-trusty

before_script:
    - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - curl 
    - wget 
    - file 
    - gzip 
    - bzip2 
    - bsdmainutils 
    - python 
    - util-linux 
    - tmux 
    - lib32gcc1 
    - libstdc++6 
    - libstdc++6:i386
    - expect

script:

    - bash lgsm/tests/tests_hldmserver.sh
    - bash lgsm/tests/tests_ts3server.sh
